#!/usr/bin/env bash

# Copyright © 2017-2021 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

usage()
{
    printf 'Usage: %s REPO\n' "${0##*/}" >&2
    exit 1
}

urlescape()
{
    perl -E '$_ = $ARGV[0]; chomp; s/\W/sprintf "%%%02x", ord $&/ge; say $_' "$@"
}

get_curl_config()
{
    printf 'header = "Authorization: token %s"\n' "$token"
    cacert=/usr/share/ca-certificates/mozilla/USERTrust_RSA_Certification_Authority.crt
    if [ -d "${cacert%/*}" ]
    then
        printf 'capath = "/nonexistent"\n'
        printf 'cacert = "%s"\n' "$cacert"
    fi
}

turl()
{
    curl \
        --silent --fail --show-error \
        -K <(get_curl_config) \
        -H 'Travis-API-Version: 3' \
        -H 'User-Agent: travis-enable (https://github.com/jwilk/travis-toolbox)' \
        "$@"
}

[ $# -eq 1 ] || usage
token="$TRAVIS_TOKEN"
repo="$1"
[ -z "${repo##*/*}" ] || repo="$USER/$repo"
xrepo=$(urlescape "$repo")

turl -X POST "https://api.travis-ci.org/repo/$xrepo/activate" > /dev/null

for t in builds_only_with_travis_yml auto_cancel_pushes auto_cancel_pull_requests
do
    turl \
        -H 'Content-Type: application/json' -d '{ "setting.value": true }' \
        -X PATCH "https://api.travis-ci.org/repo/$xrepo/setting/$t" > /dev/null
done

res=$(turl "https://api.travis-ci.org/repo/$xrepo")
jq . <<<"$res"

# vim:ts=4 sts=4 sw=4 et
