#!/bin/bash

# Copyright © 2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

usage()
{
    printf 'Usage: %s <repo> [branch]\n' "$0" >&2
    exit 1
}

urlescape()
{
    perl -E '$_ = $ARGV[0]; chomp; s/\W/sprintf "%%%02x", ord $&/ge; say $_' "$@"
}

turl()
{
    curl \
        --silent --fail --show-error \
        --cacert "$cacert" \
        -K <(printf 'header = "Authorization: token %s"\n' "$token") \
        -H 'Travis-API-Version: 3' \
        -H 'User-Agent: travis-trigger (https://github.com/jwilk/travis-toolbox)' \
        "$@"
}

[ $# -eq 1 ] || [ $# -eq 2 ] || usage
token="$TRAVIS_TOKEN"
cacert=/usr/share/ca-certificates/mozilla/DigiCert_High_Assurance_EV_Root_CA.crt
repo="$1"
[ -z "${repo##*/*}" ] || repo="$USER/$repo"
xrepo=$(urlescape "$repo")
if [ $# -eq 2 ]
then
    branch="$2"
    xbranch=$(urlescape "$branch")
else
    branch='master'
    xbranch='master'
fi
data=$(jo -- -s branch="$xbranch")
data=$(jo request="$data")
url="https://api.travis-ci.org/repo/$xrepo/requests"
res=$(turl -H 'Content-Type: application/json' -d "$data" -X POST "$url")
jq . <<<"$res"

# vim:ts=4 sts=4 sw=4 et
