#!/bin/bash

set -e -u

cacert=/usr/share/ca-certificates/mozilla/DigiCert_High_Assurance_EV_Root_CA.crt
token="$TRAVIS_TOKEN"

turl()
{
    curl \
        --silent --fail --show-error \
        --cacert "$cacert" \
        -K <(printf 'header = "Authorization: token %s"\n' "$token") \
        -H 'Travis-API-Version: 3' \
        -H 'User-Agent: travis-sync (jwilk@jwilk.net)' \
        "$@"
}

res=$(turl "https://api.travis-ci.org/user")

url=$(jq -r '.["@href"]' <<EOF
$res
EOF
)

res=$(turl -X POST "https://api.travis-ci.org$url/sync")
jq . <<EOF
$res
EOF

# vim:ts=4 sts=4 sw=4 et
