#!/usr/bin/env bash

# Copyright © 2017-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

usage()
{
    printf 'Usage: %s [-b BRANCH] REPO [INTERVAL]\n' "${0##*/}"
    printf 'Intervals: never daily weekly monthly\n'
}

urlescape()
{
    perl -E '$_ = $ARGV[0]; chomp; s/\W/sprintf "%%%02x", ord $&/ge; say $_' "$@"
}

get_curl_config()
{
    printf 'header = "Authorization: token %s"\n' "$token"
    cacert=/usr/share/ca-certificates/mozilla/COMODO_RSA_Certification_Authority.crt
    if [ -d "${cacert%/*}" ]
    then
        printf 'capath = "/nonexistent"\n'
        printf 'cacert = "%s"\n' "$cacert"
    fi
}

turl()
{
    curl \
        --silent --fail --show-error \
        -K <(get_curl_config) \
        -H 'Travis-API-Version: 3' \
        -H 'User-Agent: travis-cron (https://github.com/jwilk/travis-toolbox)' \
        "$@"
}

branch=master
while getopts 'hb:' opt
do
    case "$opt" in
        h) usage; exit 0;;
        b) branch="$OPTARG";;
        *) exit 1;;
    esac
done
shift $((OPTIND - 1))
[ $# -eq 1 ] || [ $# -eq 2 ] || {
    usage >&2
    exit 1
}
token="$TRAVIS_TOKEN"
repo="$1"
[ -z "${repo##*/*}" ] || repo="$USER/$repo"
xrepo=$(urlescape "$repo")
xbranch=$(urlescape "$branch")
interval="${2-}"
if [ -z "$interval" ] || [ "$interval" = never ]
then
    data=
elif [ "$interval" = 'daily' ] || [ "$interval" = 'weekly' ] || [ "$interval" = 'monthly' ]
then
    data=$(jo cron.interval="$interval" cron.dont_run_if_recent_build_exists@true)
else
    usage >&2
    exit 1
fi
base='https://api.travis-ci.org'
url="$base/repo/$xrepo/branch/$xbranch/cron"
jq_expr='"Repo: " + .repository.slug + "@" + .branch.name, "Interval: " + .interval, "Last run: " + .last_run, "Next run: " + .next_run, "Run if recent build exists: " + (if .dont_run_if_recent_build_exists then "no" else "yes" end)'
if [ -n "$data" ]
then
    res=$(turl -H 'Content-Type: application/json' -d "$data" -X POST "$url")
    jq -r "$jq_expr" <<<"$res"
else
    res=$(turl -X GET "$url")
    if [ -z "$interval" ]
    then
        jq -r "$jq_expr" <<<"$res"
    else
        id=$(jq '.["id"]' <<<"$res")
        turl -X DELETE "$base/cron/$id"
    fi
fi

# vim:ts=4 sts=4 sw=4 et
