#!/bin/bash

# Copyright © 2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

cacert=/usr/share/ca-certificates/mozilla/COMODO_RSA_Certification_Authority.crt
token="$TRAVIS_TOKEN"

turl()
{
    curl \
        --silent --fail --show-error \
        --capath /nonexistent --cacert "$cacert" \
        -K <(printf 'header = "Authorization: token %s"\n' "$token") \
        -H 'Travis-API-Version: 3' \
        -H 'User-Agent: travis-sync (https://github.com/jwilk/travis-toolbox)' \
        "$@"
}

res=$(turl "https://api.travis-ci.org/user")
url=$(jq -r '.["@href"]' <<<"$res")
res=$(turl -X POST "https://api.travis-ci.org$url/sync")
jq . <<<"$res"

# vim:ts=4 sts=4 sw=4 et
