#!/bin/bash

# Copyright © 2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

usage()
{
    printf 'Usage: %s\n' "$0" >&2
    exit 1
}

get_curl_config()
{
    printf 'header = "Authorization: token %s"\n' "$token"
    cacert=/usr/share/ca-certificates/mozilla/COMODO_RSA_Certification_Authority.crt
    if [ -d "${cacert%/*}" ]
    then
        printf 'capath = "/nonexistent"\n'
        printf 'cacert = "%s"\n' "$cacert"
    fi
}

turl()
{
    curl \
        --silent --fail --show-error \
        -K <(get_curl_config) \
        -H 'Travis-API-Version: 3' \
        -H 'User-Agent: travis-sync (https://github.com/jwilk/travis-toolbox)' \
        "$@"
}

[ $# -eq 0 ] || usage
token="$TRAVIS_TOKEN"
res=$(turl "https://api.travis-ci.org/user")
url=$(jq -r '.["@href"]' <<<"$res")
res=$(turl -X POST "https://api.travis-ci.org$url/sync")
jq . <<<"$res"

# vim:ts=4 sts=4 sw=4 et
