#!/usr/bin/env bash

# Copyright © 2017-2020 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

usage()
{
    printf 'Usage: %s REPO [BRANCH]\n' "${0##*/}" >&2
    exit 1
}

urlescape()
{
    perl -E '$_ = $ARGV[0]; chomp; s/\W/sprintf "%%%02x", ord $&/ge; say $_' "$@"
}

get_curl_config()
{
    printf 'header = "Authorization: token %s"\n' "$token"
    cacert=/usr/share/ca-certificates/mozilla/COMODO_RSA_Certification_Authority.crt
    if [ -d "${cacert%/*}" ]
    then
        printf 'capath = "/nonexistent"\n'
        printf 'cacert = "%s"\n' "$cacert"
    fi
}

turl()
{
    curl \
        --silent --fail --show-error \
        -K <(get_curl_config) \
        -H 'Travis-API-Version: 3' \
        -H 'User-Agent: travis-trigger (https://github.com/jwilk/travis-toolbox)' \
        "$@"
}

[ $# -eq 1 ] || [ $# -eq 2 ] || usage
token="$TRAVIS_TOKEN"
repo="$1"
[ -z "${repo##*/*}" ] || repo="$USER/$repo"
xrepo=$(urlescape "$repo")
if [ $# -eq 2 ]
then
    branch="$2"
    xbranch=$(urlescape "$branch")
else
    branch='master'
    xbranch='master'
fi
data=$(jq -n '{"request": {"branch": $branch}}' --arg branch "$xbranch")
url="https://api.travis-ci.org/repo/$xrepo/requests"
res=$(turl -H 'Content-Type: application/json' -d "$data" -X POST "$url")
jq . <<<"$res"

# vim:ts=4 sts=4 sw=4 et
